name: 'Auto Merge Dependency Updates'
description: 'Automatically merge a PR that only contains dependency updates, based on some rules.'
author: 'Tom Jenkinson'
inputs:
  repo-token:
    description: 'GitHub API token'
    default: ${{ github.token }}
  approve:
    description: 'Automatically approve the PR if it qualifies for auto merge'
    default: 'true'
  use-auto-merge:
    description: 'Enable GitHub auto merge on the PR and exit instead of waiting for the checks to complete and merging. Auto merge must be enabled on the repo, and you should make sure this is a required status check'
    default: 'false'
  merge:
    description: 'Merge the PR if it qualifies'
    default: 'true'
  merge-method:
    description: 'Merge method to use. Supported: "merge", "squash", "rebase"'
    default: 'merge'
  required-labels:
    description: 'Only merge pull requests that have one of these labels (comma-seperated)'
    default: 'dependencies,auto-merge'
outputs:
  success:
    description: '"true" if the commit meets the criteria'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'
