name: 'Auto Merge'
description: 'TODO'
author: 'Tom Jenkinson'
inputs:
  repo-token:
    required: true
    description: 'GitHub API token'
  allowed-actors:
    required: true
    description: 'Comma separated list of usernames auto merge is allowed for'
  allowed-update-types:
    description: 'Comma separated list of types of updates that are allowed. Supported: [devDependencies|dependencies]:[major|minor|patch]'
    default: 'devDependencies:minor, devDependencies:patch'
  package-block-list:
    required: false
    description: 'Comma separated list of packages that auto merge should not be allowed for'
runs:
  using: 'node12'
  main: 'dist/index.js'
