name: Test Action

on:
  - pull_request
  - pull_request_review

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-actors: tjenkinson, dependabot-preview[bot], dependabot[bot]
          package-block-list: '@actions/core, @actions/github, @octokit/webhooks'
