name: Node CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 21]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm ci
          npm run lint
          npm run build
      - name: check no diff
        run: |
          diff_files=$(git diff)
          if [[ -n "$diff_files" ]]; then
            echo "Diff:"
            echo ""
            echo "$diff_files"
            echo ""
            echo "Please run 'npm run build' locally and commit changes."
            exit 1
          fi
