name: Keep Versions Up-To-Date

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@c46540b9f3302c3b4e6a7bd622cb478fc98c52be
        env:
          GITHUB_TOKEN: '${{ github.token }}'
